[package]
name = "back"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.26.3"
json = "0.12.4"
log = "0.4.16"
env_logger = "0.9.0"
nanoid = "0.4.0"
